dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
script:
  - pylint src/
  - pytest --cov=. --cov-report xml
after_success:
  - python-codacy-coverage -r coverage.xml