'''
This module declares constants needed for this solution. This is to remove
magic numbers
'''
CRATER_CHANGE_WHEN_SUNNY = 0.9
CRATER_CHANGE_WHEN_RAINY = 1.2
CRATER_CHANGE_WHEN_WINDY = 0.0
ORBIT1_ORBIT_DISTANCE = 18
ORBIT1_CRATERS_COUNT = 20
ORBIT2_ORBIT_DISTANCE = 20
ORBIT2_CRATERS_COUNT = 10
